"""add supports_function_call and tool_configs

Revision ID: 49c9b8b11f5e
Revises: cf8a39d60b90
Create Date: 2026-08-24 11:14:23.620509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c9b8b11f5e'
down_revision: Union[str, Sequence[str], None] = 'cf8a39d60b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tool_key', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_configs_tool_key'), 'tool_configs', ['tool_key'], unique=False)
    op.create_index(op.f('ix_tool_configs_user_id'), 'tool_configs', ['user_id'], unique=False)
    op.add_column('model_configs', sa.Column('supports_function_call', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_configs', 'supports_function_call')
    op.drop_index(op.f('ix_tool_configs_user_id'), table_name='tool_configs')
    op.drop_index(op.f('ix_tool_configs_tool_key'), table_name='tool_configs')
    op.drop_table('tool_configs')
    # ### end Alembic commands ###
